server:
  port: 8888
spring:
  application:
    name: computer_accessories
  datasource:
    url: jdbc:mysql://localhost:3306/computer_accessories
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    add-properties: true
    restart:
      log-condition-evaluation-delta: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 838931501142-qmucmmbdh6d27ct61s9h4asevrre11kp.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "http://localhost:8888/api/v1/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangduyphuong30102002@gmail.com
    password: gyiiincystvdipam
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    serverUrl: http://localhost:${server.port}
    serverName: Server Dev
    title: API Document
    version: 1.0.0


jwt:
  expiryTime: 86400000 # a day
  refresh-token:
    expiryTime: 604800000 # 7 day
  secretKey: 947ba682032c9b9d4e376b4fe2c3c053657d39af82e738a7d2916a5d0df36bb4

app:
  auth:
    jwt:
      access-token-secret-key:
      refresh-token-secret-key:
      access-token-expiration-in-min: 60
      refresh-token-expiration-in-day: 30
      refresh-token-rotation: false
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8888
      - http://localhost:3000